apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: adp
  namespace: adp
spec:
  version: 7.1.0
  nodes:
  - nodeCount: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
    podTemplate:
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 2Gi
              cpu: 1
    volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
---
apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  name: adp
  namespace: adp
spec:
  version: 7.1.0
  nodeCount: 1
  podTemplate:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
  elasticsearchRef:
    name: adp
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: adp-kibana
  namespace: adp
spec:
  rules:
  - host: adp-kibana.innovation.cloud.statcan.ca
    http:
      paths:
      - backend:
          serviceName: adp-kibana
          servicePort: 5601
        path: /*
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: adp-es
  namespace: adp
spec:
  rules:
  - host: adp-es.innovation.cloud.statcan.ca
    http:
      paths:
      - backend:
          serviceName: adp-es
          servicePort: 9200
        path: /*
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: adp-es
  namespace: adp
spec:
  host: adp-es
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 9200
      tls:
        mode: SIMPLE # initiates HTTPS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: adp-kibana
  namespace: adp
spec:
  host: adp-kibana
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 5601
      tls:
        mode: DISABLE
